[package]
name = "chip_8"
version = "0.1.0"
authors = ["am-khan <akbir.94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
piston_window = "0.98.0"